### PR TITLE
Fix the module not loading.

### PR DESCRIPTION
**Pull request by YelehaUwU**

### CODE REVIEW

**Comment by EinS4ckZwiebeln** [comment]
How exactly does that fix the issue?

**Comment by YelehaUwU** [comment]
The enabled variable is missing in the category, making the module ineffective.

**Comment by EinS4ckZwiebeln** [comment]
> The enabled variable is missing in the category, making the module ineffective.

Ah I see, good catch!

**Comment by YelehaUwU** [comment]
Can you approve it?

**Comment by EinS4ckZwiebeln** [comment]
> Can you approve it?

Yes, but have you read my review??

**Review by EinS4ckZwiebeln — CHANGES_REQUESTED** [review]

**Review by YelehaUwU — COMMENTED** [review]
Yes, you're correct.

**Review by EinS4ckZwiebeln — APPROVED** [review]

**Pull request merged**
